'use strict';

var authOnly = require('./account/only');
var ownerOnly = require('./author/roleOnly')(['owner']);
var articlesOnly = require('./author/roleOnly')(['owner', 'articles']);
var weekliesOnly = require('./author/roleOnly')(['owner', 'weeklies']);

module.exports = [
  { route: '/', action: 'articles/home' },
  { route: '/p/:page([1-9][0-9]{0,})', action: 'articles/home' },
  { route: '/all/feed', ignore: true },
  { route: '/articles/feed', ignore: true },
  { route: '/articles/history', action: 'articles/history' },
  { route: '/articles/archives', ignore: true },
  { route: '/articles/first', action: 'articles/first' },
  { route: '/articles/last', action: 'articles/last' },
  { route: '/articles/random', action: 'articles/random' },
  { route: '/articles/tagged/:tags', action: 'articles/tagged' },
  { route: '/articles/search/:terms', action: 'articles/search' },
  { route: '/articles/search/:terms/tagged/:tags', action: 'articles/searchTagged' },
  { route: '/articles/:year(\\d{4})/:month([01]\\d)/:day([0-3]\\d)', action: 'articles/dated' },
  { route: '/articles/:year(\\d{4})/:month([01]\\d)', action: 'articles/dated' },
  { route: '/articles/:year(\\d{4})', action: 'articles/dated' },
  { route: '/articles/:slug', action: 'articles/article' },
  { route: '/weekly', action: 'weekly/home' },
  { route: '/weekly/feed', ignore: true },
  { route: '/weekly/sponsor', action: 'weekly/sponsor' },
  { route: '/weekly/history', action: 'weekly/history' },
  { route: '/weekly/first', action: 'weekly/first' },
  { route: '/weekly/last', action: 'weekly/last' },
  { route: '/weekly/random', action: 'weekly/random' },
  { route: '/weekly/:slug', action: 'weekly/issue' },
  { route: '/about', action: 'marketing/about' },
  { route: '/speaking', action: 'speaking/home' },
  { route: '/opensource', action: 'opensource/home' },
  { route: '/books', action: 'books/home' },
  { route: '/books/javascript-application-design', action: 'books/javascript-application-design' },
  { route: '/presentations', action: 'speaking/presentations' },
  { route: '/presentations/:slug', action: 'speaking/presentation' },
  { route: '/subscribe', action: 'marketing/subscribe' },
  { route: '/subscribed', action: 'marketing/subscribed' },
  { route: '/unsubscribed', action: 'marketing/unsubscribed' },
  { route: '/account/login', action: 'account/login' },
  { route: '/account/login/:provider', ignore: true },
  { route: '/account/logout', ignore: true },
  { route: '/account/bio', action: 'account/bio', middleware: authOnly },
  { route: '/author/articles', action: 'author/articles/review', middleware: articlesOnly },
  { route: '/author/articles/new', action: 'author/articles/compose', middleware: articlesOnly },
  { route: '/author/articles/:slug', action: 'author/articles/compose', middleware: articlesOnly },
  { route: '/author/weeklies', action: 'author/weeklies/review', middleware: weekliesOnly },
  { route: '/author/weeklies/new', action: 'author/weeklies/assemble', middleware: weekliesOnly },
  { route: '/author/weeklies/:slug', action: 'author/weeklies/assemble', middleware: weekliesOnly },
  { route: '/author/announcements', action: 'author/announcements', middleware: ownerOnly },
  { route: '/author/engagements', action: 'author/engagements', middleware: ownerOnly },
  { route: '/author/engagements/new', action: 'author/engagements-new', middleware: ownerOnly },
  { route: '/author/presentations', action: 'author/presentations', middleware: ownerOnly },
  { route: '/author/presentations/new', action: 'author/presentations-new', middleware: ownerOnly },
  { route: '/author/oss', action: 'author/oss', middleware: ownerOnly },
  { route: '/author/oss/new', action: 'author/oss-new', middleware: ownerOnly },
  { route: '/author/logs/:page([1-9][0-9]{0,})?', action: 'author/logs', middleware: ownerOnly },
  { route: '/author/subscribers/:page([1-9][0-9]{0,})?', action: 'author/subscribers', middleware: ownerOnly },
  { route: '/author/settings', action: 'author/settings', middleware: ownerOnly },
  { route: '/privacy', action: 'marketing/privacy' },
  { route: '/bf/:shortlink?', ignore: true },
  { route: '/s/:shortlink?', ignore: true },
  { route: '/offline', action: 'error/offline' },
  { route: '/*', action: 'error/not-found' }
];
