#!/bin/bash

echo "packer: nginx"
sudo mkdir -p /var/log/nginx
sudo chown $INSTANCE_USER /var/log/nginx
sudo chmod -R 755 /var/log/nginx
sudo apt-get install nginx -y

echo "packer: nginx as a service"
sudo update-rc.d nginx defaults

echo "packer: nvm"
curl https://raw.githubusercontent.com/creationix/nvm/$NVM_VERSION/install.sh | bash
. $HOME/.nvm/nvm.sh

echo '[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh' >> $HOME/.bashrc

echo "packer: nodejs"
nvm install $NODE_VERSION
nvm alias default $NODE_VERSION
npm update -g npm

echo "packer: precaching server dependencies"
mkdir -p $HOME/app/precache
cp -r /tmp/mailtube $HOME/app/mailtube
cp $HOME/app/mailtube/package.json $HOME/app/precache
npm install --prefix $HOME/app/precache --production

if [ $? -ne 0 ]
then
  echo "packer: npm install failed. bailing"
  exit 1
fi
