#!/bin/bash

echo "packer: pulling up mailtube"
mkdir -p $HOME/app/mailtube
cp -r /tmp/mailtube $HOME/app/mailtube

echo "packer: elasticsearch + logstash + kibana as services"
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable elasticsearch.service
sudo /bin/systemctl enable logstash.service
sudo /bin/systemctl enable kibana.service

echo "packer: elasticsearch x-pack"
sudo service elasticsearch stop
sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack --batch
sudo service elasticsearch start
sleep 20s

echo "packer: elasticsearch password"
KIBANA_CONF=/opt/kibana/config/kibana.yml

curl \
  -XPUT \
  -u $ES_USERNAME:changeme \
  -d "{ \"password\": \"$ES_PASSWORD\" }" \
    "http://localhost:9200/_xpack/security/user/$ES_USERNAME/_password"

echo "elasticsearch.username: \"$ES_USERNAME\"" | sudo tee -a $KIBANA_CONF > /dev/null
echo "elasticsearch.password: \"$ES_PASSWORD\"" | sudo tee -a $KIBANA_CONF > /dev/null

echo "packer: elasticsearch license"
curl \
  -XPUT \
  -u $ES_USERNAME:$ES_PASSWORD \
  -d @$HOME/app/mailtube/elasticsearch/license.json \
  "http://localhost:9200/_xpack/license"

echo "packer: kibana x-pack"
sudo /opt/kibana/bin/kibana-plugin install x-pack
sudo tar jxf /opt/kibana/installedPlugins/x-pack/.phantom/phantomjs-1.9.8-linux-x86_64.tar.bz2
sudo chown -R kibana:kibana /opt/kibana

echo "packer: nginx"
sudo mkdir -p /var/log/nginx
sudo chown $INSTANCE_USER /var/log/nginx
sudo chmod -R 755 /var/log/nginx
sudo apt-get -y install nginx

echo "packer: nginx as a service"
sudo update-rc.d nginx defaults

echo "packer: nvm"
curl https://raw.githubusercontent.com/creationix/nvm/$NVM_VERSION/install.sh | bash
. $HOME/.nvm/nvm.sh

echo '[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh' >> $HOME/.bashrc

echo "packer: nodejs"
nvm install $NODE_VERSION
nvm alias default $NODE_VERSION
npm update -g npm

echo "packer: precaching server dependencies"
mkdir -p $HOME/app/precache
cp $HOME/app/mailtube/package.json $HOME/app/precache
cd $HOME/app/precache
npm install --production

if [ $? -ne 0 ]
then
  echo "packer: npm install failed. bailing"
  exit 1
fi
