#!/bin/bash

: "${NODE_ENV:="staging"}"

NAME="ponyfoo-$NODE_ENV"
INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$NAME" \
  | jq -r .Reservations[0].Instances[0].InstanceId)

aws ec2 terminate-instances --instance-ids $INSTANCE_ID
aws ec2 delete-tags --resources $INSTANCE_ID --tags Key=Name
