#!/usr/bin/env node

'use strict';

process.chdir(__dirname);

var contra = require('contra');
var winston = require('winston');
var models = require('./models');
var pkg = require('./package.json');
var logging = require('./lib/logging');
var db = require('./lib/db');
var articleService = require('./services/article');
var articlePublishService = require('./services/articlePublish');
var t, p = 0;
var m;

logging.configure();
db(operational);

function operational () {
  winston.info('Worker %s executing job@%s', process.pid, pkg.version);
  m = models();
  m.Article.find({ status: 'publish' }, found);
}

function found (err, articles) {
  if (err || !articles || articles.length === 0) {
    done(err); return;
  }
  t = articles.length;
  winston.info('Found %s articles queued for publication', t);
  contra.each(articles, 2, single, done);
}

function single (article, next) {
  contra.waterfall([
    function attemptPublication (next) {
      articlePublishService.publish(article, next);
    },
    function notifySubscribers (published, next) {
      if (published) {
        article.save(saved); // save the status change first!
      } else {
        next();
      }

      function saved (err) {
        if (!err) {
          p++;
          articleService.campaign(article, promoted);
          winston.info('Published "%s".', article.title);
        } else {
          next(err);
        }
      }

      function promoted (err) {
        if (err) {
          winston.error('Article campaign failed for "%s".\n%s', article.title, err.stack || err);
        }
        next(err);
      }
    }
  ], next);
}

function done (err) {
  if (err) {
    winston.error('Cron job failed!', err.stack || err);
  }
  winston.info('Published %s/%s articles.', p, t);
  process.exit(err ? 1 : 0);
}
